<?php

$cropRequirements = [
    'Ajo' => [
        'ph' => 6.0,
        'mo' => 3.0,
        'fosforo' => 25,
        'al3' => 0.2,
        'precipitacion_anual' => 1200,
        'temperatura' => 20,
        'humedad' => 70,
    ],
    'Algodón' => [
        'ph' => 6.5,
        'mo' => 2.0,
        'fosforo' => 18,
        'al3' => 0.5,
        'precipitacion_anual' => 1000,
        'temperatura' => 27,
        'humedad' => 65,
    ],
    'Arroz de secano' => [
        'ph' => 5.5,
        'mo' => 3.5,
        'fosforo' => 20,
        'al3' => 0.6,
        'precipitacion_anual' => 1300,
        'temperatura' => 25,
        'humedad' => 80,
    ],
    'Arveja' => [
        'ph' => 6.5,
        'mo' => 2.5,
        'fosforo' => 22,
        'al3' => 0.3,
        'precipitacion_anual' => 1100,
        'temperatura' => 18,
        'humedad' => 70,
    ],
    'Batata' => [
        'ph' => 5.6,
        'mo' => 2.0,
        'fosforo' => 15,
        'al3' => 0.4,
        'precipitacion_anual' => 1400,
        'temperatura' => 24,
        'humedad' => 75,
    ],
    'Canola' => [
        'ph' => 6.5,
        'mo' => 2.0,
        'fosforo' => 18,
        'al3' => 0.3,
        'precipitacion_anual' => 1200,
        'temperatura' => 18,
        'humedad' => 70,
    ],
    'Caña de azúcar' => [
        'ph' => 6.5,
        'mo' => 3.0,
        'fosforo' => 22,
        'al3' => 0.2,
        'precipitacion_anual' => 1500,
        'temperatura' => 26,
        'humedad' => 75,
    ],
    'Cebolla de cabeza' => [
        'ph' => 6.8,
        'mo' => 2.5,
        'fosforo' => 25,
        'al3' => 0.1,
        'precipitacion_anual' => 1300,
        'temperatura' => 20,
        'humedad' => 70,
    ],
    'Frutilla' => [
        'ph' => 5.8,
        'mo' => 3.0,
        'fosforo' => 20,
        'al3' => 0.3,
        'precipitacion_anual' => 1200,
        'temperatura' => 18,
        'humedad' => 80,
    ],
    'Girasol' => [
        'ph' => 6.5,
        'mo' => 2.0,
        'fosforo' => 18,
        'al3' => 0.3,
        'precipitacion_anual' => 1100,
        'temperatura' => 25,
        'humedad' => 65,
    ],
    'Habilla' => [
        'ph' => 6.2,
        'mo' => 2.5,
        'fosforo' => 22,
        'al3' => 0.2,
        'precipitacion_anual' => 1200,
        'temperatura' => 19,
        'humedad' => 70,
    ],
    'Stevia' => [
        'ph' => 5.5,
        'mo' => 2.8,
        'fosforo' => 18,
        'al3' => 0.5,
        'precipitacion_anual' => 1400,
        'temperatura' => 24,
        'humedad' => 80,
    ],
    'Locote' => [
        'ph' => 6.5,
        'mo' => 2.5,
        'fosforo' => 22,
        'al3' => 0.2,
        'precipitacion_anual' => 1300,
        'temperatura' => 26,
        'humedad' => 65,
    ],
    'Maíz' => [
        'ph' => 6.2,
        'mo' => 3.0,
        'fosforo' => 20,
        'al3' => 0.3,
        'precipitacion_anual' => 1200,
        'temperatura' => 25,
        'humedad' => 70,
    ],
    'Mandioca' => [
        'ph' => 5.0,
        'mo' => 3.0,
        'fosforo' => 15,
        'al3' => 0.6,
        'precipitacion_anual' => 1500,
        'temperatura' => 26,
        'humedad' => 80,
    ],
    'Maní' => [
        'ph' => 6.5,
        'mo' => 2.0,
        'fosforo' => 18,
        'al3' => 0.3,
        'precipitacion_anual' => 1200,
        'temperatura' => 27,
        'humedad' => 65,
    ],
    'Menta' => [
        'ph' => 6.2,
        'mo' => 2.8,
        'fosforo' => 22,
        'al3' => 0.2,
        'precipitacion_anual' => 1300,
        'temperatura' => 19,
        'humedad' => 80,
    ],
    'Papa' => [
        'ph' => 5.5,
        'mo' => 3.0,
        'fosforo' => 20,
        'al3' => 0.4,
        'precipitacion_anual' => 1200,
        'temperatura' => 16,
        'humedad' => 80,
    ],
    'Poroto' => [
        'ph' => 6.3,
        'mo' => 2.5,
        'fosforo' => 20,
        'al3' => 0.2,
        'precipitacion_anual' => 1300,
        'temperatura' => 24,
        'humedad' => 70,
    ],
    'Sésamo' => [
        'ph' => 6.2,
        'mo' => 2.0,
        'fosforo' => 15,
        'al3' => 0.4,
        'precipitacion_anual' => 1100,
        'temperatura' => 26,
        'humedad' => 65,
    ],
    'Soja' => [
        'ph' => 6.5,
        'mo' => 2.5,
        'fosforo' => 20,
        'al3' => 0.2,
        'precipitacion_anual' => 1200,
        'temperatura' => 27,
        'humedad' => 65,
    ],
    'Sorgo para grano' => [
        'ph' => 6.2,
        'mo' => 2.0,
        'fosforo' => 18,
        'al3'
    ]
];
